### ISSUE TITLE
Stop sliding when only having 1 image?

### ISSUE THREAD

**Issue by zruu** [jedrzejchalubek/glidejs#158]
How can I make the Glide.js stop sliding when only having one image? Is it possible?

**Comment by zackmax** [comment]
I too am looking for this solution. Using this to display images on a news article. Will only need functionality when more than one item is in the slideshow. Did you ever figure something out zruu?

**Comment by zackmax** [comment]
I found this thread digging through older posts: https://github.com/jedrzejchalubek/glidejs/issues/54

However, the code has likely been updated since because I can't figure out where that snippet of code goes. Maybe admin has some ideas?

**Comment by jedrzejchalubek** [comment]
Issue you mentioning applies to version 1.*, not current. You can't apply it in version 2.*.

Solution is pretty straightforward. We need to escape eailer from `Run.make()` method, if number of slides is less or equal one.

Added to milestone, but pull requests are welcome :)

**Comment by jedrzejchalubek** [comment]
Fixed with 040feee.

**Comment by zackmax** [comment]
Hi! Thank you for the recent commit. It stops the slide effect with just one image. But it still shows the Prev/Next control buttons. Any idea how to not show these? 

Thanks in advance for your help!

**Comment by zackmax** [comment]
Hi! I want to check in and see if you had a solution to prevent the Prev/Next controls from showing when there is only one image?

**Comment by marcwieland95** [comment]
Hi, sorry for the waiting. I'll go into it this issue soon.
Until now you could count the images and hide the arrows when just one image is available.

**Comment by marcwieland95** [comment]
The arrow gets a "disabled" class. So just apply custom CSS to hide it.
Removing the markup on the plugin side is not a good solution in my opinion.

**Comment by zackmax** [comment]
@marcwieland95 I can't believe I missed that! Thanks! Simple solution.

**Comment by alokinsijo** [comment]
i am using 2.0.3 version glide js. How to solve this issue in this version.
